name: Deploy

#When to run
on:
  push:
    branches:
      - main

#What jobs to do
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      -name: Install dependencies
        run: npm install
      - name: Deploy code
        run: npm run deploy